---

- name: Running consumer with parameters
  debug:
    msg:
      - "connection_string: {{perf_connection}}"
      - "client_name: {{client_name}}"
      - "perf_destName: {{perf_destName}}"
      - "perf_consumer_heap_min: {{perf_consumer_heap_min}}"
      - "perf_consumer_heap_max: {{perf_consumer_heap_max}}"
      - "perf_consumer_clients: {{perf_consumer_clients}}"
      - "perf_consumer_sessTransacted: {{perf_consumer_sessTransacted}}"
      - "perf_consumer_sessAckMode: {{perf_consumer_sessAckMode}}"

- name: Configure the consumer settings
  template: 
    src: templates/amqp-consumer.properties.j2
    dest: "{{amq_perf_test_path}}/src/main/resources/{{client_name}}-amqp-consumer.properties"
  
- name: Start the performance test consumer
  args:
    chdir: "{{amq_perf_test_path}}"
  shell: |
    export MAVEN_OPTS="-Xmx{{perf_consumer_heap_min}} -Xms{{perf_consumer_heap_max}}" 
    {{ 'source scl_source enable rh-maven36 && '  if ansible_facts.distribution_major_version  == '7' }} nohup mvn activemq-perf:consumer \
      -DsysTest.propsConfigFile=src/main/resources/{{client_name}}-amqp-consumer.properties \
      > {{amq_perf_test_path}}/target/{{client_name}}-consumer.log 2>&1 &

- name: Check the consumer started
  shell: jps -mlvV
  register: proclist
  failed_when: "client_name not in proclist.stdout"

- name: Display consumer processes after start
  debug: 
    msg: "Processes running on {{ansible_hostname}} \n{{proclist.stdout}}"


